### ISSUE TITLE
Initialiser un site statique

### ISSUE THREAD

**Issue by hadrylouis** [dil-classroom/projet-louis_mondaini_nunez#21]
- Créer la commande `statique init /mon/site`
- Cette commande permet d'initialiser le site statique dans le dossier `/mon/site`

En d’autres termes, la sous-commande init pourrait créer ou enrichir le dossier nommé `/mon/site` avec un fichier
de configuration config.yaml contenant des informations générales liées au site (titre, description, domaine, etc.) et
un fichier Markdown index.md contenant une page d’accueil avec des métadonnées et du contenu

**Comment by NunezTania** [comment]
Durée estimée:

Optimiste: 15min
Attendue: 45min
Pessimiste: 60min
