### ISSUE TITLE
Compiler un site statique

### ISSUE THREAD

**Issue by hadrylouis** [dil-classroom/projet-louis_mondaini_nunez#22]
- Créer le compilateur qui traite tous les fichiers du site et utilise le parser créé prcédemment
- Le compilateur doit être lancé avec :
`$ statique build /mon/site`
En d’autres termes, la sous-commande build crée un dossier `/mon/site/build` contenant des fichiers HTML
correspondant au contenu de chaque page du site statique. Certains fichiers comme les fichiers de configuration ne
doivent pas être ajoutés au dossier build. Exemple 

![image](https://user-images.githubusercontent.com/26306723/158786591-5983f0d5-18f9-4f99-9a14-6a6f0caa97b3.png)

Le tableau suivant illustre la compilation d’un fichier markdown en HTML (les métadonnées peuvent être ignorées
pour le moment):

![image](https://user-images.githubusercontent.com/26306723/158786666-940d174f-31b6-46c4-a0df-549810f7ebdf.png)

**Comment by damianomondaini** [comment]
Durée estimée:

Optimiste: 30min
Attendue: 45min
Pessimiste: 60min

**Comment by hadrylouis** [comment]
Done
