### ISSUE TITLE
Modifier la commande init afin qu'elle crée le dossier template et son contenu menu.html et layout.html

### ISSUE THREAD

**Issue by NunezTania** [dil-classroom/projet-louis_mondaini_nunez#52]
### Description
Modifier la commande init afin qu'elle crée le dossier template et son contenu menu.html et layout.html

### Durée
| Optimiste  | Pessimiste   | Attentu  | Effecuté ✔ |
|------------|-------------|----------|---------|
|  30min      |    45min     |  30min  |     20min          |

**Comment by hadrylouis** [comment]
Done
