### ISSUE TITLE
Manuel utilisateur

### ISSUE THREAD

**Issue by NunezTania** [dil-classroom/projet-louis_mondaini_nunez#63]
### Description
Rédiger un manuel utilisateur reproductible qui guide l’utilisateur lors de la création d’un site statique avec votre
générateur

### Durée
| Optimiste  | Pessimiste   | Attentu  | Effecuté ✔ |
|------------|-------------|----------|---------|
|      1h 30  |        4h      |       2h       |       30min        |

**Comment by hadrylouis** [comment]
Done
