### ISSUE TITLE
Code coverage

### ISSUE THREAD

**Issue by NunezTania** [dil-classroom/projet-louis_mondaini_nunez#64]
### Description
Configurez Jacoco ou un outil équivalent pour calculer le degré de couverture de votre code par des tests unitaires et
d’intégration. Ajoutez les données de couverture à votre rapport

### Tâches
-

### Durée
| Optimiste  | Pessimiste   | Attentu  | Effecuté ✔ |
|------------|-------------|----------|---------|
|     1h         |       2h       |       1h30       |        30min       |

**Comment by hadrylouis** [comment]
Done
