### ISSUE TITLE
Code quality

### ISSUE THREAD

**Issue by NunezTania** [dil-classroom/projet-louis_mondaini_nunez#65]
### Description
Configurez LGTM8, SonarQube ou un outil équivalent pour détecter des bugs et des vulnérabilités dans votre code.
Expliquez en quoi l’un de ces outils vous aura permis d’améliorer vos pratiques de développement.

### Durée
| Optimiste  | Pessimiste   | Attentu  | Effecuté ✔ |
|------------|-------------|----------|---------|
|    45min    |       2h       |  1h15      |       1h        |

**Comment by hadrylouis** [comment]
Done
