### ISSUE TITLE
Code benchmarking

### ISSUE THREAD

**Issue by NunezTania** [dil-classroom/projet-louis_mondaini_nunez#66]
### Description
Utilisez JMH pour mesurer les performances de votre compilateur markdown ou de votre moteur de rendu. Utilisez
VisualVM pour profiler une exécution de la commande build. Incluez ces données dans votre rapport et discutez
d’une éventuelle optimisation (sans nécessairement l’implémenter).

### Tâches
- Installer un outil de benchmark
- Prise en main de l'outil et quelques tests
- Lancement du benchmarking sur le projet
- Analyse des résultats

### Durée
| Optimiste  | Pessimiste   | Attentu  | Effecuté ✔ |
|------------|-------------|----------|---------|
|    1h30      |       3h       |      2h        |               |

**Comment by hadrylouis** [comment]
Finalement, par manque de temps, le benchmarking n'a pas été fait avec JMH mais InteliJ qui propose directement un outils de ce type avec moins de fonctionnalités
