### ISSUE TITLE
Handlebars is not handling includes

### ISSUE THREAD

**Issue by damianomondaini** [dil-classroom/projet-louis_mondaini_nunez#80]
### Description

Handlebars ne supporte plus l'include du menu

### Tâches

- Investiguer pourquoi Handlebars ne fonctionne plus correctement
- Résoudre le problème

### Durée
| Optimiste  | Pessimiste   | Attentu  | Effecuté ✔ |
|------------|-------------|----------|---------|
|        5min          |  30min                  |  15min            |         10min      |

### Dépendances d'autres tâches

Aucune

**Comment by hadrylouis** [comment]
Done thx @damianomondaini
